-- MySQL Script generated by MySQL Workbench
-- Mon Apr  7 10:37:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `E-mail` VARCHAR(100) NOT NULL,
  `PhoneNumber` VARCHAR(15) NULL,
  `FullName` VARCHAR(100) NOT NULL,
  `Surname` VARCHAR(100) NOT NULL,
  `BirthDate` DATETIME NULL,
  `Gender` TINYINT NULL,
  `Password` VARCHAR(1024) NOT NULL,
  `NewsOn` TINYINT NOT NULL DEFAULT 0,
  `LaRenzaPoints` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `BageId` INT NULL,
  `FilterId` INT NULL,
  `ImageId` INT NOT NULL,
  `CategoryId` INT NULL,
  `IsGlobal` TINYINT ZEROFILL NOT NULL DEFAULT 1,
  `IsActive` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Category_Category1_idx` (`CategoryId` ASC, `id` ASC) VISIBLE,
  CONSTRAINT `fk_Category_Category1`
    FOREIGN KEY (`CategoryId` , `id`)
    REFERENCES `mydb`.`Category` (`id` , `CategoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CategoryImage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CategoryImage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Path` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_CategoryImage_Categories1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Category` (`ImageId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Favorite` (
  `UserId` INT NOT NULL,
  `ProductId` INT NOT NULL,
  INDEX `fk_Favorites_User1_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_Favorites_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ModelId` INT NOT NULL,
  `SizeId` INT NOT NULL,
  `ColorId` INT NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `Quantity` INT NOT NULL,
  `Code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Favorites1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Favorite` (`ProductId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coupon` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(300) NOT NULL,
  `Price` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `UserId` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `OrderName` VARCHAR(45) NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `CompletedAt` DATETIME NULL,
  `PaymentMethod` INT NOT NULL,
  `DeliveryMethod` INT NOT NULL,
  `DeliveryId` INT NOT NULL,
  `CuponsId` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Orders_User1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_Orders_Cupon1_idx` (`CuponsId` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Cupon1`
    FOREIGN KEY (`CuponsId`)
    REFERENCES `mydb`.`Coupon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Size` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CommentImage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CommentImage` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Path` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ProductId` INT NOT NULL,
  `UserId` INT NOT NULL,
  `Text` VARCHAR(1000) NOT NULL,
  `Rating` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `LikesAmount` INT NOT NULL,
  `ColorId` INT NULL,
  `SizeId` INT NULL,
  `ImageId` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Comment_Products1_idx` (`ProductId` ASC) VISIBLE,
  INDEX `fk_Comment_User1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_Comment_Sizes1_idx` (`SizeId` ASC) VISIBLE,
  INDEX `fk_Comment_CommentImage1_idx` (`ColorId` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_Products1`
    FOREIGN KEY (`ProductId`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Sizes1`
    FOREIGN KEY (`SizeId`)
    REFERENCES `mydb`.`Size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_CommentImage1`
    FOREIGN KEY (`ColorId`)
    REFERENCES `mydb`.`CommentImage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ImageProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ImageProduct` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Path` VARCHAR(100) NOT NULL,
  `ProductId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_ImagesProducts_Products1_idx` (`ProductId` ASC) VISIBLE,
  CONSTRAINT `fk_ImagesProducts_Products1`
    FOREIGN KEY (`ProductId`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductSize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductSize` (
  `ProductId` INT NOT NULL,
  `SizeId` INT NOT NULL,
  PRIMARY KEY (`ProductId`, `SizeId`),
  INDEX `fk_ProductsSizes_Sizes1_idx` (`SizeId` ASC) VISIBLE,
  UNIQUE INDEX `ProductId_UNIQUE` (`ProductId` ASC) VISIBLE,
  UNIQUE INDEX `SizeId_UNIQUE` (`SizeId` ASC) VISIBLE,
  CONSTRAINT `fk_ProductsSizes_Products1`
    FOREIGN KEY (`ProductId`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductsSizes_Sizes1`
    FOREIGN KEY (`SizeId`)
    REFERENCES `mydb`.`Size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductCategory` (
  `ProductId` INT NOT NULL,
  `CategoryId` INT NOT NULL,
  PRIMARY KEY (`ProductId`, `CategoryId`),
  INDEX `fk_ProductCategory_Categories1_idx` (`CategoryId` ASC) VISIBLE,
  UNIQUE INDEX `CategoryId_UNIQUE` (`CategoryId` ASC) VISIBLE,
  UNIQUE INDEX `ProductId_UNIQUE` (`ProductId` ASC) VISIBLE,
  CONSTRAINT `fk_ProductCategory_Products1`
    FOREIGN KEY (`ProductId`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductCategory_Categories1`
    FOREIGN KEY (`CategoryId`)
    REFERENCES `mydb`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Like` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `UserId` INT NOT NULL,
  `CommentId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Likes_User1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_Likes_Comment1_idx` (`CommentId` ASC) VISIBLE,
  CONSTRAINT `fk_Likes_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Likes_Comment1`
    FOREIGN KEY (`CommentId`)
    REFERENCES `mydb`.`Comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderItem` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `OrderId` INT NOT NULL,
  `ProductId` INT NOT NULL,
  `Quantity` INT NOT NULL,
  `ColorId` INT NOT NULL,
  `SizeId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_OrderItems_Orders1_idx` (`OrderId` ASC) VISIBLE,
  INDEX `fk_OrderItems_Products1_idx` (`ProductId` ASC) VISIBLE,
  INDEX `fk_OrderItems_Sizes1_idx` (`SizeId` ASC) VISIBLE,
  CONSTRAINT `fk_OrderItems_Orders1`
    FOREIGN KEY (`OrderId`)
    REFERENCES `mydb`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderItems_Products1`
    FOREIGN KEY (`ProductId`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderItems_Sizes1`
    FOREIGN KEY (`SizeId`)
    REFERENCES `mydb`.`Size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Color` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Path` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Colors_Comment1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Comment` (`ColorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colors_OrderItems1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`OrderItem` (`ColorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductColor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductColor` (
  `ColorId` INT NOT NULL,
  `ProductsId` INT NOT NULL,
  PRIMARY KEY (`ColorId`, `ProductsId`),
  INDEX `fk_ProductsColors_Products1_idx` (`ProductsId` ASC) VISIBLE,
  UNIQUE INDEX `ColorId_UNIQUE` (`ColorId` ASC) VISIBLE,
  UNIQUE INDEX `ProductsId_UNIQUE` (`ProductsId` ASC) VISIBLE,
  CONSTRAINT `fk_ProductsColors_Colors1`
    FOREIGN KEY (`ColorId`)
    REFERENCES `mydb`.`Color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductsColors_Products1`
    FOREIGN KEY (`ProductsId`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `SecondName` VARCHAR(45) NOT NULL,
  `FullName` VARCHAR(45) NOT NULL,
  `Street` VARCHAR(100) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `HouseNum` VARCHAR(15) NOT NULL,
  `PostIndex` VARCHAR(10) NOT NULL,
  `AdditionalInfo` VARCHAR(150) NULL,
  `PhoneNumber` VARCHAR(15) NOT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Adress_User1_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_Adress_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Address_Orders1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Order` (`DeliveryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Invoice` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FullName` VARCHAR(45) NOT NULL,
  `SecondName` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `PostIndex` VARCHAR(10) NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `HouseNumber` VARCHAR(15) NOT NULL,
  `IsDigital` TINYINT NOT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Invoice_User1_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_Invoice_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserCoupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserCoupon` (
  `UserId` INT NOT NULL,
  `CuponId` INT NOT NULL,
  INDEX `fk_UsersCupons_User1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_UsersCupons_Cupon1_idx` (`CuponId` ASC) VISIBLE,
  CONSTRAINT `fk_UsersCupons_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsersCupons_Cupon1`
    FOREIGN KEY (`CuponId`)
    REFERENCES `mydb`.`Coupon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Model` (
  `id` INT NOT NULL,
  `Name` VARCHAR(250) NOT NULL,
  `Description` VARCHAR(500) NOT NULL,
  `MaterialInfo` VARCHAR(200) NOT NULL,
  `StartDate` DATE NOT NULL,
  `Rate` DECIMAL(1,1) NULL,
  `Bage` VARCHAR(15) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Model_Product1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Product` (`ModelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(60) NOT NULL,
  `Identifier` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
